Add iam based access for dynamodb
xmidt-org/argus pull request #769
Opened 2024-08-07 12:41 UTC by chaitanyasingla-dt

2024-08-07 15:33 UTC, Sachin4403 requested changes

2024-08-07 15:33 UTC, Sachin4403 commented on store/dynamodb/db.go
> +	IamBasedAccessEnabled bool
Rename  this flag to roleBasedAccess.

2024-08-07 15:33 UTC, Sachin4403 commented on store/dynamodb/db.go
> +func getAwsRegionForCassandra(config Config) (string, error) {
Please change this function name.

2024-08-08 07:16 UTC, chaitanyasingla-dt commented on store/dynamodb/db.go
> +	IamBasedAccessEnabled bool
Done

2024-08-08 07:17 UTC, chaitanyasingla-dt commented on store/dynamodb/db.go
> +func getAwsRegionForCassandra(config Config) (string, error) {
Done

2024-08-08 07:23 UTC, Sachin4403 approved these changes

2024-08-08 07:24 UTC, Sachin4403 commented
@schmidtw 
Please review and merge this pull request.

2024-08-08 08:22 UTC, Sachin4403 approved these changes

2024-08-12 09:56 UTC, closed without merging